export const RouterVariable = Object.freeze({
    BASE_URL: '',
    BASE_URL_LOGIN: 'auth/login',
    BASE_URL_PRODUCT_LIST: 'product/product-list',
    BASE_URL_CREATE_PRODUCT: 'product/create-product',
    BASE_URL_EDIT_PRODUCT: 'product/edit-product',
    BASE_URL_USER_LIST: 'user',
    BASE_URL_EDIT_INFORMATION: 'user-information',
    BASE_URL_CREATE_USER: 'create-user',
    BASE_URL_EDIT_USER: 'edit-user',
    BASE_URL_CUSTOMER_VIEW: 'customer-view',
    BASE_URL_CREATE_CUSTOMER: 'create-customer',
    BASE_URL_CREATE_STORE_LOCATION: 'create-store-location',
    BASE_URL_EDIT_STORE_LOCATION: 'edit-store-location',
    BASE_URL_CREATE_PROMOTION_LIST: 'promotion-list',
    BASE_URL_CREATE_PROMOTION: 'create-promotion',
    BASE_URL_EDIT_PROMOTION: 'edit-promotion',
    BASE_URL_COUPON_LIST: 'coupon-list',
    BASE_URL_CREATE_COUPON: 'create-coupon',
    BASE_URL_EDIT_COUPON: 'edit-coupon',
    BASE_URL_CREATE_CONVERSATION: 'facebook-chatbot/create-conversation',
    BASE_URL_CONVERSATION_VIEW: 'facebook-chatbot/conversation-view',
    BASE_URL_CREATE_BROADCAST: 'facebook-chatbot/create-broadcast',
    BASE_URL_BROADCAST_VIEW: 'facebook-chatbot/broadcast-view',
    BASE_URL_CREATE_REPLY_TEMPLATE: 'facebook-chatbot/create-reply-template',
    BASE_URL_REPLY_TEMPLATE_VIEW: 'facebook-chatbot/reply-template-view',
    BASE_URL_WARRANTY_LIST: 'warranty-list',
    BASE_URL_EDIT_WARRANTY: 'edit-warranty',
    BASE_URL_MANAGE_PAGE: 'facebook-chatbot/manage-page',

    BASE_URL_MANAGE_BOT: 'line-chatbot/manage-bot',
    BASE_URL_CREATE_LINE_CONVERSATION_LIST: 'line-chatbot/conversation-list',
    BASE_URL_CREATE_LINE_CONVERSATION: 'line-chatbot/create-conversation',
    BASE_URL_EDIT_LINE_CONVERSATION: 'line-chatbot/edit-conversation',

});